import MyBookings from "@/components/booking/MyBookings";
import React from "react";
export const metadata = {
  title: " Next Stay Bookings Page",
  description: "Generated by create next app",
};
const BookingsPage = () => {
  return (
    <div>
      <MyBookings />
    </div>
  );
};

export default BookingsPage;
