import HotelDetails from "@/components/hotel/details/HotelDetails";
import React from "react";
export const metadata = {
  title: " Next Stay details Page",
  description: "Generated by create next app",
};
async function fetchHotelDetails(id) {
  const response = await fetch(
    `${process.env.NEXT_PUBLIC_BASE_URL}/hotels/${id}`,
    {
      cache: "no-store",
    }
  );

  if (!response.ok) throw new Error("Failed to fetch hotel details");

  return response.json();
}
const HotelDetailsPage = async ({ params }) => {
  const { id } = params;
  const hotel = await fetchHotelDetails(id);
  return (
    <div>
      <HotelDetails hotel={hotel} />
    </div>
  );
};

export default HotelDetailsPage;
